dimensions:
	Azimuth = 720 ;
	Gate = 960 ;
variables:
	float Azimuth(Azimuth) ;
		Azimuth:Units = "Degrees" ;
	float Elevation(Azimuth) ;
		Elevation:Units = "Degrees" ;
	float Beamwidth(Azimuth) ;
		Beamwidth:Units = "Degrees" ;
	float GateWidth(Azimuth) ;
		GateWidth:Units = "Meters" ;
	float TxPower(Azimuth) ;
		TxPower:Units = "dBm" ;
	float Corrected_Intensity(Azimuth, Gate) ;
		Corrected_Intensity:Units = "dBZ" ;

// global attributes:
		:TypeName = "Corrected_Intensity" ;
		:DataType = "RadialSet" ;
		:Latitude = 35.1800994873047 ;
		:Longitude = -97.4337005615234 ;
		:Height = 342 ;
		:Time = 1244863777 ;
		:FractionalTime = 0. ;
		:attributes = "NyquistVelocity vcp radarName ColorMap" ;
		:NyquistVelocity-unit = "MetersPerSecond" ;
		:NyquistVelocity-value = "16.05" ;
		:vcp-unit = "dimensionless" ;
		:vcp-value = "OUVCP21_1deg" ;
		:radarName-unit = "dimensionless" ;
		:radarName-value = "OKU" ;
		:RangeToFirstGate = 0 ;
		:RangeToFirstGateUnits = "Meters" ;
		:RadarParameters = "PRF PulseWidth MaximumRange" ;
		:PRF-unit = "Hertz" ;
		:PRF-value = 1180 ;
		:PulseWidth-unit = "MicroSeconds" ;
		:PulseWidth-value = 0.8 ;
		:MaximumRange-unit = "KiloMeters" ;
		:MaximumRange-value = 120.f ;
		:Z_Calibration = 0.f ;
		:Zdr_Calibration = 0.f ;
		:C_Calibration = 32.f ;
		:ColorMap-unit = "dimensionless" ;
		:ColorMap-value = "Reflectivity" ;
		:Elevation = 1.5 ;
		:ElevationUnits = "Degrees" ;
		:MissingData = -99900. ;
		:RangeFolded = -99901. ;
		:MoreRadarParameters = "AntennaSpeed ClutterFilter" ;
		:AntennaSpeed-DegreesPerSecond = 15.f ;
		:ClutterFilter = "No Filter" ;
		:CalibrationParameters = "ZCal ZdrOffset NoiseSampleH NoiseSampleV" ;
		:ZCal-dB = -32.f ;
		:ZdrOffset-dB = 0.f ;
		:NoiseSampleH-value = 2.25f ;
		:NoiseSampleV-value = 2.01f ;
		:CensoringParameters = "LogNoiseThreshold CCOR SQIThreshold" ;
		:LogNoiseThreshold-dB = 0.0625f ;
		:CCOR-dB = 60.f ;
		:SQIThreshold-percent = 0.f ;
		:ConversionPlugin = "Vol2NetCDF v1.2 for EDGE 5.3" ;
		:ContactInformation = "http://arrc.ou.edu/ouprime" ;